server:
  port: 8761
 
spring:
   application:
      name: pocgma-discovery-server
    


eureka:
 client:
  register-with-eureka: true
  fetch-registry: false
 server:
    enableSelfPreservation: false

logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF



 